# Generated by Django 3.0.7 on 2020-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_ID',
            field=models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, verbose_name='Employee_ID'),
        ),
    ]
