# Generated by Django 3.0.7 on 2020-06-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0005_remove_customertoca_caccount_last_access_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertoca',
            name='CAccount_Last_Access_Date',
            field=models.DateTimeField(auto_now=True, verbose_name='CAccount_Last_Access_Date'),
        ),
    ]
