# Generated by Django 3.0.7 on 2020-06-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0006_customertoca_caccount_last_access_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertosa',
            name='SAccount_Last_Access_Date',
        ),
    ]
