# Generated by Django 3.0.7 on 2020-06-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0009_remove_savingaccount_saccount_last_access_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrelease',
            name='id',
        ),
        migrations.AlterField(
            model_name='loanrelease',
            name='Loan_Release_ID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Loan_Release_ID'),
        ),
    ]
