# Generated by Django 3.0.7 on 2020-06-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0010_auto_20200627_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_ID',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='Employee_ID'),
        ),
    ]
