# Generated by Django 3.0.7 on 2020-07-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0011_auto_20200629_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertoca',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankManagement.Customer'),
        ),
        migrations.AlterField(
            model_name='customertoloan',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankManagement.Customer'),
        ),
        migrations.AlterField(
            model_name='customertosa',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankManagement.Customer'),
        ),
    ]
