# Generated by Django 3.0.7 on 2020-07-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0013_auto_20200702_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkaccount',
            name='CAccount_Overdraft',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='CAccount_Overdraft'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='Loan_Total',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Loan_Total'),
        ),
        migrations.AlterField(
            model_name='loanrelease',
            name='Loan_Release_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Loan_Release_Amount'),
        ),
        migrations.AlterField(
            model_name='savingaccount',
            name='SAccount_Balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='SAccount_Balance'),
        ),
        migrations.AlterField(
            model_name='savingaccount',
            name='SAccount_Interest_Rate',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='SAccount_Interest_Rate'),
        ),
    ]
