# Generated by Django 3.0.7 on 2020-07-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0014_auto_20200702_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Employee_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BankManagement.Employee'),
        ),
    ]
