# Generated by Django 3.0.7 on 2020-07-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0015_auto_20200703_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Employee_ID',
        ),
    ]
