# Generated by Django 3.0.7 on 2020-07-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagement', '0016_remove_customer_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Employee_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BankManagement.Employee'),
        ),
    ]
